FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY services/auth ./services/auth
COPY services/shared ./services/shared

EXPOSE 8085

CMD ["npx", "nodemon", "services/auth/auth-service.js"]
