FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY services/cart ./services/cart
COPY services/shared ./services/shared

EXPOSE 8082

CMD ["npx", "nodemon", "services/cart/cart-service.js"]
